# Generated by Django 4.0.5 on 2022-06-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('kind', models.CharField(choices=[('knitting', 'KNITTING')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('upper_car', 'UPPER_CAR'), ('lower_car', 'LOWER_CAR'), ('needle_bed', 'NEEDLE_BED'), ('needle_selector', 'NEEDLE_SELECTOR'), ('transport_bag', 'TRANSPORT_BAG'), ('left_car', 'LEFT_CAR'), ('right_car', 'RIGHT_CAR'), ('accesories', 'ACCESORIES')], max_length=20)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=150)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('reference', models.PositiveIntegerField(blank=True, default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('img', models.URLField(blank=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.sector')),
            ],
        ),
    ]
