# Generated by Django 4.0.5 on 2022-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
