# Generated by Django 4.0.5 on 2022-06-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_machine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
