# Generated by Django 4.0.5 on 2022-06-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_sector_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
