# Generated by Django 4.0.5 on 2022-06-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_alter_sector_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='description',
        ),
        migrations.AlterField(
            model_name='sector',
            name='img',
            field=models.URLField(),
        ),
    ]
