# Generated by Django 4.0.5 on 2022-06-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_remove_sector_description_alter_sector_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='photo',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='part',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='part',
            name='img',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='part',
            name='reference',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
