# Generated by Django 4.0.5 on 2022-06-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_alter_part_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='url_seller',
            field=models.URLField(default=''),
        ),
    ]
