# Generated by Django 4.0.5 on 2022-06-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_part_url_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='url_seller',
            field=models.URLField(default='', max_length=400),
        ),
    ]
