# Generated by Django 4.0.5 on 2022-07-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_alter_part_url_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['reference']},
        ),
    ]
