# Generated by Django 4.0.5 on 2022-06-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='data_json',
        ),
    ]
