# Generated by Django 4.0.5 on 2022-06-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_data_order_data_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
