# Generated by Django 4.0.5 on 2022-06-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_created_order_modified_order_send_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('no pago', 'NO PAGO'), ('revision', 'REVISION'), ('aprobado', 'APROBADO')], default='no pago', max_length=20),
        ),
    ]
