# Generated by Django 4.0.5 on 2022-06-27 14:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='bills/'),
        ),
    ]
